- name: "update apt packages."
  become: yes
  apt:
     update_cache: yes
     cache_valid_time: 86400

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

# - name: Copy files
#   become: true
#   copy:
#     src: /root/project/artifact.tar.gz
#     dest: /home/ubuntu/artifact.tar.gz
 
- name: Unarchive
  become: true
  shell : |
    cd /home/ubuntu/
    tar xvzf artifact.tar.gz -C .
 
# - name: "run server"
#   become: true
#   shell : |
#     cd /home/ubuntu/
#     npm install
#     pm2 stop all
#     pm2 start npm -- start

- name: Install dependencies(Node)
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes
  
- name: Install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes
  
- name: Extract artifact
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: Run Server
  become: yes
  shell: |
    npm install
    pm2 stop all
    pm2 start npm -- start